name: Release

on: [push]

concurrency:
  group: all-release
  cancel-in-progress: true

jobs:
  check-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: |
          npm ci

      # - name: Build
      #   run: |
      #     npm run build

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx auto shipit --dry-run > output.txt 2>&1

          # Print the raw output for inspection
          echo "Raw output:"
          cat output.txt

          # Print each line with line numbers and special characters visible
          echo "Output with special characters visible:"
          cat -A output.txt

      - name: Check for version bump
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
          OUTPUT=$(npx auto shipit --dry-run 2>&1 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g")
          echo "Cleaned Output:"
          echo "$OUTPUT"

          # Check if the output contains the desired string
          if echo "$OUTPUT" | grep -q "Calculated version bump: none"; then
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "No version bump needed"
          else
            echo "should_release=true" >> $GITHUB_OUTPUT
            echo "Version bump needed"
          fi

  # release:
  #   runs-on: ubuntu-latest
  #   if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Prepare repository
  #       run: git fetch --unshallow --tags

  #     - name: Use Node.js 22.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 22.x

  #     - name: Cache node modules
  #       uses: actions/cache@v4
  #       with:
  #         path: node_modules
  #         key: npm-deps-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-deps-${{ hashFiles('package-lock.json') }}

  #     - name: Install Dependencies
  #       run: |
  #         npm ci

  #     - name: Build
  #       run: |
  #         npm run build

  #     - name: Create Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: |
  #         npx auto shipit
